services:
  cbr-custom:
    build:
      context: ../../..
      dockerfile: ./deploy/docker/cbr__defensible_governance/Dockerfile

    platform: linux/amd64
    container_name: cbr__defensible_governance
    tty: true
    environment:
      - PORT=3000

    ports:
      - "5116:3000"
    volumes:
      - ../../../cbr__defensible_governance/custom:/app/custom
      - ./cbr__defensible_governance__run_locally.sh:/app/cbr__defensible_governance__run_locally.sh
      - ../../../cbr__defensible_governance/custom/cbr_content/en/web-pages/:/usr/local/lib/python3.12/site-packages/cbr_content/en/web-pages/
      - ../../../cbr__defensible_governance/custom/cbr_content/en/web-site/:/usr/local/lib/python3.12/site-packages/cbr_content/en/web-site/
      - ../../../cbr__defensible_governance/custom/cbr_static/assets/defensible-governance:/usr/local/lib/python3.12/site-packages/cbr_static/assets/defensible-governance

    #pull_policy: always
    env_file:
      - .env
    entrypoint: ["./cbr__defensible_governance__run_locally.sh"]


# docker pull --platform linux/amd64 diniscruz/cbr_website_beta:latest
# docker compose up --build
# docker exec -it {contained id} bash
# run
#    export python_packages=/usr/local/lib/python3.12/site-packages
#    cp -R ./custom/* $python_packages