name: 'Update CBR Content'
description: 'Update CBR Content (from Git)'

runs:
  using: 'composite'
  steps:

    - name: clone repo
      shell: bash
      run: |                                
        export python_packages=$(python -c "import site; print(site.getsitepackages()[0])")
        echo "set python_packages to  $python_packages"        
        
        tmp_folder=/tmp                                      

        cd $tmp_folder
        git clone --branch dev https://github.com/the-cyber-boardroom/cbr-custom--defensible-governance.git /tmp/cbr-custom--defensible-governance
                
        cp -Rv $tmp_folder/cbr-custom--defensible-governance/cbr__defensible_governance/custom/* $python_packages


        
